export const Types = {
  GET_WALLET: 'GET_WALLET',
  SET_ETH: 'SET_ETH',
  SELECT_WALLET_TYPE: 'SELECT_WALLET_TYPE',
  SET_PROVIDER: 'SET_PROVIDER',
  ERROR_MESSAGE: 'ERROR_MESSAGE',
  DASH_PRIMARY_STATS: 'DASH_PRIMARY_STATS',
  ZELDA_STATS: 'ZELDA_STATS',
  ZELDA_HISTORY: 'ZELDA_HISTORY',
  ZELDA_CLAIM: 'ZELDA_CLAIM',
  XATT_STATS: 'XATT_STATS',
  XATT_USER_STAKE: 'XATT_USER_STAKE',
};
